# Generated by Django 5.1.4 on 2025-01-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_states_links',
            name='state_name',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
    ]
