# Generated by Django 5.1.4 on 2025-01-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0002_all_states_links_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_states_links',
            name='Link_to_real_estate',
            field=models.URLField(default='Default'),
            preserve_default=False,
        ),
    ]
