# Generated by Django 5.1.4 on 2025-01-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0003_all_states_links_link_to_real_estate'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities_real_estate_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('link_to_city', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='cities_real_estate',
        ),
    ]
