# Generated by Django 5.1.4 on 2025-01-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0004_cities_real_estate_links_delete_cities_real_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_profile_details',
            name='agent_phone',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
