# Generated by Django 5.1.4 on 2025-01-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0005_agent_profile_details_agent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_profile_details',
            name='agent_email',
            field=models.EmailField(default='none', max_length=254),
            preserve_default=False,
        ),
    ]
