# Generated by Django 5.1.4 on 2025-01-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0006_agent_profile_details_agent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_profile_details',
            name='agent_license_number',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
