# Generated by Django 5.1.4 on 2025-01-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0007_agent_profile_details_agent_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_profile_details',
            name='agent_license_number',
            field=models.CharField(blank=True, default='No License Found', max_length=200, null=True),
        ),
    ]
