# Generated by Django 5.1.4 on 2025-01-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0008_alter_agent_profile_details_agent_license_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, default='No name Found', max_length=200, null=True)),
                ('agent_license', models.CharField(blank=True, default='No License Found', max_length=300, null=True)),
                ('agent_phone', models.CharField(blank=True, default='No Phone Found', max_length=300, null=True)),
                ('agent_email', models.EmailField(blank=True, default='No Email Found', max_length=254, null=True)),
                ('spoken_language', models.CharField(blank=True, default='No Language Found', max_length=500, null=True)),
                ('agent_office_location', models.CharField(blank=True, default='No Office Found', max_length=500, null=True)),
                ('agent_about_info', models.TextField(blank=True, default='No About Info Found', null=True)),
                ('IG_link', models.URLField(blank=True, default='No IG Found', null=True)),
                ('FB_link', models.URLField(blank=True, default='No FB Found', null=True)),
                ('Twitter_link', models.URLField(blank=True, default='No X Found', null=True)),
                ('agent_designations', models.TextField(blank=True, default='No Designation Info Found', null=True)),
                ('agent_website', models.URLField(blank=True, default='No agent website', null=True)),
                ('agent_role', models.CharField(blank=True, default='No Role Found', max_length=500, null=True)),
                ('google_map_link', models.CharField(blank=True, default='No map link Found', max_length=500, null=True)),
                ('current_listings', models.TextField(blank=True, default='No Homes or Listings Found', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent_profile_details',
            name='agent_url',
            field=models.URLField(default='default url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all_states_links',
            name='has_state_grabbed_all_urls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cities_real_estate_links',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cities_real_estate_links',
            name='state_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='real_estate_scraper_app.all_states_links'),
        ),
        migrations.AlterField(
            model_name='agent_profile_details',
            name='agent_email',
            field=models.EmailField(blank=True, default='No Email Found', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agent_profile_details',
            name='agent_name',
            field=models.CharField(blank=True, default='No agent name Found', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent_profile_details',
            name='agent_phone',
            field=models.CharField(blank=True, default='No Phone Found', max_length=200, null=True),
        ),
    ]
