# Generated by Django 5.1.4 on 2025-01-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_scraper_app', '0009_agent_records_agent_profile_details_agent_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentURLWithError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, default='No name Found', max_length=200, null=True)),
                ('urls_with_errors', models.TextField(blank=True, default=' ', help_text='agent url failed to process', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent_profile_details',
            name='city_name',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent_records',
            name='state_code',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cities_real_estate_links',
            name='agents_found_status',
            field=models.CharField(blank=True, default='No Agents Found', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cities_real_estate_links',
            name='urls_with_errors',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
